#!/usr/bin/env bash
# A script that installs nginx on your server
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' | /var/www/html/index.html > /dev/null
service nginx restart
