#!/usr/bin/env bash
# A script that installs nginx on your server
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' | /var/www/html/index.html
sed -i '/server_name _;/a \\n    location /redirect_me/ {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default
service nginx start
service nginx restart
