#!/usr/bin/env bash
# A script that installs nginx on your server
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' | /var/www/html/index.html > /dev/null
sed -i "/^\sserver_name.*/a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
service nginx start
sudo service nginx restart
