#!/usr/bin/env bash
# A script that installs nginx on your server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}/" /etc/nginx/sites-available/default
sudo service nginx restart
