#!/usr/bin/env bash
# A script that installs nginx on your server
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' | /var/www/html/index.html > /dev/null
sed -i "/^\sserver_name.*/a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default;
echo 'Ceci n'\''est pas une page' > /var/www/html/custom_404.html
sed -i '/^\s*server_name _;/ a\\n\tlocation / {\n\t\terror_page 404 /custom_404.html;\n\t\terror_page 403 404 =404;\n\t}' /etc/nginx/sites-available/default
service nginx start
service nginx restart
