#!/usr/bin/env bash
# A script that installs nginx on your server
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' | /var/www/html/index.html
sed -i '/server_name _;/a \\n    location /redirect_me/ {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sed -i '/error_page 404/i \\n        location = /404.html {\n            root /usr/share/nginx/html;\n            internal;\n        }\n' /etc/nginx/sites-available/default
sed -i '/location = \/404.html {/a \            return 404 "\nCeci n'\''est pas une page\n";\n' /etc/nginx/sites-available/default
service nginx start
service nginx restart
