#!/usr/bin/env bash
# install load balancer with round robin
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
yes enter | sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get install -y haproxy
sudo service haproxy start
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 183519-web-01 54.160.84.211:80 check
    server 183519-web-02 54.172.244.75:80 check
EOF
sudo service haproxy restart
