#!/usr/bin/env bash
# MySQL root password
mysql_password="$1"

# Get the current date in the required format
current_date=$(date +'%d-%m-%Y')

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name
archive_name="$current_date.tar.gz"

# Generate MySQL dump
mysqldump -u root -p"$mysql_password" --all-databases > "$dump_file"

# Compress the dump file into a .tar.gz archive
tar -czvf "$archive_name" "$dump_file"
