#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
FILE="/etc/passwd"
cat $FILE |
while read -r line; do
    username=$(cut -d : -f 1 <<< "$line")
    userid=$(cut -d : -f 3 <<< "$line")
    userhome=$(cut -d : -f 6 <<< "$line")
    echo "$username:$userid:$userhome"
done
