#!/usr/bin/env bash
#  displays the content of the file /etc/passwd, using the while loop + IFS.
FILE="/etc/passwd"
OLDIFS="$IFS"
cat $FILE |
while read -r line; do
    IFS=":"
    read -ra array <<< "$line"
    gang_sentence="The user ${array[0]} is part of the ${array[3]} gang"
    location_sentence="lives in ${array[5]} and rides ${array[6]}"
    security_sentence="${array[2]}'s place is protected by the passcode ${array[1]}"
    more_info="more info about the user here: ${array[4]}"
    echo "$gang_sentence, $location_sentence. $security_sentence, $more_info"
    IFS=$OLDIFS
done
