#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 20
i=0
while ((i < 20)); do
    case "$i" in
        3) echo -e "4\nbad luck from China" ;;
        8) echo -e "9\nbad luck from Japan" ;;
        16) echo -e "17\nbad luck from Italy" ;;
        *) echo "Best School" ;;
    esac
    ((i++))
done
