#!/usr/bin/env bash
# changes the facebook and localhost ip address on a system
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts # /etc/hosts
sed -i '$a 8.8.8.8 facebook.com' /etc/hosts
cp -f ~/hosts.new /etc/hosts
